spring.application.name=inge2

spring.datasource.url=jdbc:sqlite:../database/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amdevs67@gmail.com
spring.mail.password=CONTRASENA_ELIMINADA
        
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mercadopago.access-token=APP_USR-6818119826975837-052016-b2ad221231a198f26ce298b1cf71405e-3414946629

app.frontend-url=https://nx2c13cq-5173.brs.devtunnels.ms/
app.backend-url=https://nx2c13cq-8080.brs.devtunnels.ms/