spring.application.name=inge2

spring.datasource.url=jdbc:sqlite:../database/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mercadopago.access-token=APP_USR-6818119826975837-052016-b2ad221231a198f26ce298b1cf71405e-3414946629
mercado.public.key=APP_USR-7bbbfd89-6c70-4d85-a025-e26a1ac65063
app.frontend-url=${http://localhost:5173}
app.backend-url=${APP_BACKEND_URL:http://localhost:8080}

jwt.secret=luCJJXBLcNWR0O8L8X5e2useo1L46xzpeZVfUf/Ytr4=
jwt.expiration=86400000
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}